mission_requirements = [
	["5 Polizeiwache", "3 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "1 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "3 Dienstgruppenleitung-Erweiterung"],
	["8 Feuerwache", "4 Polizeiwache", "6 Rettungswache"],
	["8 Feuerwache", "7 Polizeiwache", "6 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["2 Feuerwache", "8 Polizeiwache"],
	["2 Feuerwache", "8 Polizeiwache"],
	["4 Feuerwache", "8 Polizeiwache", "3 Rettungswache"],
	["4 Feuerwache", "8 Polizeiwache"],
	["7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["8 Feuerwache", "5 Polizeiwache", "3 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "5 Polizeiwache", "3 Dienstgruppenleitung-Erweiterung"],
	["20 Feuerwache", "5 Polizeiwache", "3 Dienstgruppenleitung-Erweiterung"],
	["7 Feuerwache", "5 Polizeiwache", "3 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Rettungswache"],
	["7 Rettungswache"],
	["7 Rettungswache"],
	["5 Polizeiwache", "1 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["7 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "1 Rettungswache", "1 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["9 Rettungswache"],
	["9 Rettungswache"],
	["9 Rettungswache"],
	["9 Rettungswache"],
	["18 Feuerwache", "9 Polizeiwache", "9 Rettungswache", "3 THW-Ortsverband"],
	["18 Feuerwache", "9 Polizeiwache", "9 Rettungswache", "3 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["18 Feuerwache", "9 Polizeiwache", "9 Rettungswache"],
	["1 Bereitschaftspolizei"],
	["1 Bereitschaftspolizei"],
	["1 Bereitschaftspolizei"],
	["1 Polizeiwache", "1 Bereitschaftspolizei"],
	["7 Polizeiwache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["1 Bereitschaftspolizei"],
	["1 Polizeiwache", "1 Bereitschaftspolizei"],
	["7 Polizeiwache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["1 Polizeiwache", "1 Bereitschaftspolizei"],
	["7 Polizeiwache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "3 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["30 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "5 Polizeiwache", "4 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["25 Feuerwache", "5 Polizeiwache", "9 Rettungswache", "1 THW-Ortsverband"],
	["25 Feuerwache", "7 Polizeiwache", "9 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["3 Polizeiwache", "1 Rettungswache", "1 Bereitschaftspolizei"],
	["7 Polizeiwache", "1 Rettungswache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "1 Polizeihubschrauberstation"],
	["7 Polizeiwache", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Polizeiwache", "1 Polizeihubschrauberstation", "3 Dienstgruppenleitung-Erweiterung"],
	["1 Feuerwache", "5 Polizeiwache", "1 Rettungswache", "1 Polizeihubschrauberstation", "3 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["12 Feuerwache", "1 Polizeiwache", "10 Rettungswache"],
	["9 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "5 Polizeiwache", "4 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "4 Polizeiwache", "6 Rettungswache"],
	["6 Feuerwache", "7 Polizeiwache", "6 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "3 Polizeiwache", "6 Rettungswache"],
	["6 Feuerwache", "7 Polizeiwache", "6 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "2 Polizeiwache", "1 Rettungswache", "2 Wasserrettung"],
	["4 Feuerwache", "5 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "3 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "3 Polizeiwache", "1 Rettungswache", "3 Wasserrettung"],
	["5 Feuerwache", "7 Polizeiwache", "1 Rettungswache", "3 Wasserrettung", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "3 Polizeiwache", "10 Rettungswache", "3 Wasserrettung"],
	["5 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "3 Wasserrettung", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "2 Polizeiwache", "1 Rettungswache", "2 Wasserrettung"],
	["4 Feuerwache", "5 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "3 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "3 Polizeiwache", "1 Rettungswache", "3 Wasserrettung"],
	["5 Feuerwache", "7 Polizeiwache", "1 Rettungswache", "3 Wasserrettung", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "3 Polizeiwache", "10 Rettungswache", "3 Wasserrettung"],
	["5 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "3 Wasserrettung", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["12 Feuerwache", "7 Polizeiwache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["2 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "1 Bereitschaftspolizei"],
	["2 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["9 Rettungswache"],
	["10 Feuerwache", "3 Polizeiwache", "6 Rettungswache"],
	["10 Feuerwache", "7 Polizeiwache", "6 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["2 Feuerwache", "5 Polizeiwache", "3 Rettungswache", "3 Bereitschaftspolizei"],
	["2 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "3 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["1 Feuerwache", "6 Polizeiwache", "3 Rettungswache", "1 Bereitschaftspolizei"],
	["1 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["2 Feuerwache", "5 Polizeiwache", "3 Rettungswache", "3 Bereitschaftspolizei"],
	["2 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "3 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["2 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "1 Bereitschaftspolizei"],
	["2 Feuerwache", "15 Polizeiwache", "4 Rettungswache", "1 Bereitschaftspolizei", "10 Dienstgruppenleitung-Erweiterung"],
	["5 Polizeiwache", "1 Bereitschaftspolizei", "1 Polizeihubschrauberstation"],
	["7 Polizeiwache", "1 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "7 Rettungswache"],
	["14 Feuerwache", "5 Polizeiwache", "7 Rettungswache"],
	["14 Feuerwache", "7 Polizeiwache", "7 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["30 Feuerwache", "6 Polizeiwache", "10 Rettungswache", "3 THW-Ortsverband"],
	["30 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "5 Polizeiwache", "3 Dienstgruppenleitung-Erweiterung"],
	["25 Feuerwache", "5 Polizeiwache", "8 Rettungswache", "3 THW-Ortsverband"],
	["25 Feuerwache", "7 Polizeiwache", "8 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Polizeiwache", "3 Rettungswache", "3 Bereitschaftspolizei", "1 Polizeihubschrauberstation"],
	["15 Polizeiwache", "3 Rettungswache", "3 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "10 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "10 Rettungswache"],
	["10 Feuerwache", "10 Rettungswache"],
	["3 Feuerwache", "7 Polizeiwache", "1 Rettungswache", "1 Bereitschaftspolizei", "2 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["25 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["3 Polizeiwache", "1 Bereitschaftspolizei"],
	["7 Polizeiwache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["3 Polizeiwache", "1 MEK-Wache"],
	["7 Polizeiwache", "1 MEK-Wache", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Polizeiwache", "1 SEK-Wache"],
	["7 Polizeiwache", "1 SEK-Wache", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["8 Polizeiwache", "1 SEK-Wache", "1 Rettungswache", "1 Polizeihubschrauberstation"],
	["8 Polizeiwache", "1 SEK-Wache", "1 Rettungswache", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Polizeiwache", "1 MEK-Wache", "1 Polizeihubschrauberstation"],
	["7 Polizeiwache", "1 MEK-Wache", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["9 Polizeiwache", "1 SEK-Wache", "3 Rettungswache"],
	["9 Polizeiwache", "1 SEK-Wache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "2 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["1 MEK-Wache"],
	["16 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["12 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "5 Polizeiwache", "1 Polizeihubschrauberstation", "2 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["14 Feuerwache", "5 Polizeiwache", "1 Werkfeuerwehr", "5 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "3 Polizeiwache", "10 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["14 Feuerwache", "7 Polizeiwache", "2 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "5 Polizeiwache", "5 Rettungswache", "2 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["20 Feuerwache", "10 Polizeiwache", "15 Rettungswache"],
	["20 Feuerwache", "10 Polizeiwache", "15 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["3 Feuerwache", "5 Polizeiwache", "2 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["16 Feuerwache", "4 Polizeiwache", "7 Rettungswache"],
	["16 Feuerwache", "7 Polizeiwache", "7 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Polizeiwache", "1 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "5 Polizeiwache", "2 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["20 Feuerwache", "10 Polizeiwache", "10 Rettungswache", "5 THW-Ortsverband"],
	["20 Feuerwache", "15 Polizeiwache", "10 Rettungswache", "5 THW-Ortsverband", "10 Dienstgruppenleitung-Erweiterung"],
	["7 Feuerwache", "5 Polizeiwache", "4 Rettungswache", "3 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["3 Polizeiwache", "1 Bereitschaftspolizei"],
	["7 Polizeiwache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["27 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "2 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["1 Feuerwache", "3 Polizeiwache", "1 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "5 Polizeiwache", "1 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["30 Feuerwache", "6 Polizeiwache", "1 Werkfeuerwehr", "10 Rettungswache", "3 THW-Ortsverband"],
	["30 Feuerwache", "15 Polizeiwache", "1 Werkfeuerwehr", "10 Rettungswache", "3 THW-Ortsverband", "10 Dienstgruppenleitung-Erweiterung"],
	["3 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "10 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "10 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "10 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "2 Polizeiwache", "9 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "9 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "2 Polizeiwache", "9 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "9 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "2 Polizeiwache", "9 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "9 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["14 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "4 Polizeiwache", "11 Rettungswache", "1 Bereitschaftspolizei", "1 Polizeihubschrauberstation"],
	["13 Feuerwache", "7 Polizeiwache", "11 Rettungswache", "1 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["16 Feuerwache", "9 Polizeiwache", "46 Rettungswache"],
	["16 Feuerwache", "15 Polizeiwache", "46 Rettungswache", "10 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "5 Polizeiwache", "15 Rettungswache"],
	["11 Feuerwache", "7 Polizeiwache", "15 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "2 Polizeiwache", "10 Rettungswache"],
	["6 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["9 Polizeiwache", "10 Rettungswache"],
	["9 Polizeiwache", "10 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "4 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "1 Polizeihubschrauberstation"],
	["4 Feuerwache", "7 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "4 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "1 Polizeihubschrauberstation"],
	["4 Feuerwache", "7 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["12 Feuerwache", "8 Polizeiwache", "9 Rettungswache"],
	["12 Feuerwache", "15 Polizeiwache", "9 Rettungswache", "10 Dienstgruppenleitung-Erweiterung"],
	["8 Feuerwache", "3 Polizeiwache", "10 Rettungswache", "3 THW-Ortsverband"],
	["8 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "4 Polizeiwache", "11 Rettungswache"],
	["13 Feuerwache", "7 Polizeiwache", "11 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "3 Polizeiwache", "1 Polizeihubschrauberstation", "2 THW-Ortsverband", "1 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "3 Polizeiwache", "1 Polizeihubschrauberstation", "2 THW-Ortsverband", "1 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "6 Polizeiwache", "5 Wasserrettung", "3 THW-Ortsverband"],
	["15 Feuerwache", "15 Polizeiwache", "5 Wasserrettung", "3 THW-Ortsverband", "10 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "6 Polizeiwache", "5 Wasserrettung", "3 THW-Ortsverband"],
	["15 Feuerwache", "15 Polizeiwache", "5 Wasserrettung", "3 THW-Ortsverband", "10 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "5 Polizeiwache", "2 Rettungswache", "1 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["1 Polizeiwache", "1 Bereitschaftspolizei"],
	["18 Feuerwache", "4 Polizeiwache", "1 Werkfeuerwehr", "6 Rettungswache", "1 THW-Ortsverband"],
	["18 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "6 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "3 Polizeiwache", "8 Rettungswache", "3 THW-Ortsverband"],
	["10 Feuerwache", "7 Polizeiwache", "8 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["30 Feuerwache", "5 Polizeiwache", "1 Werkfeuerwehr", "10 Rettungswache", "1 Polizeihubschrauberstation", "3 THW-Ortsverband"],
	["30 Feuerwache", "15 Polizeiwache", "1 Werkfeuerwehr", "10 Rettungswache", "1 Polizeihubschrauberstation", "3 THW-Ortsverband", "10 Dienstgruppenleitung-Erweiterung"],
	["8 Feuerwache", "5 Polizeiwache", "2 Rettungswache", "1 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["16 Feuerwache", "4 Polizeiwache", "14 Rettungswache", "3 THW-Ortsverband"],
	["16 Feuerwache", "7 Polizeiwache", "14 Rettungswache", "3 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "2 Polizeiwache", "8 Rettungswache", "2 THW-Ortsverband"],
	["13 Feuerwache", "7 Polizeiwache", "8 Rettungswache", "2 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "1 Polizeiwache", "2 Wasserrettung", "1 THW-Ortsverband"],
	["7 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "3 THW-Ortsverband", "1 Rettungshundestaffel", "5 Dienstgruppenleitung-Erweiterung"],
	["25 Feuerwache", "5 Polizeiwache", "9 Rettungswache", "1 THW-Ortsverband", "1 Rettungshundestaffel"],
	["25 Feuerwache", "7 Polizeiwache", "9 Rettungswache", "1 THW-Ortsverband", "1 Rettungshundestaffel", "5 Dienstgruppenleitung-Erweiterung"],
	["1 Feuerwache", "5 Polizeiwache", "1 Rettungswache", "1 Polizeihubschrauberstation", "1 Rettungshundestaffel", "3 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "4 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "1 Polizeihubschrauberstation", "1 Rettungshundestaffel"],
	["4 Feuerwache", "7 Polizeiwache", "1 Rettungswache", "2 Wasserrettung", "1 Polizeihubschrauberstation", "1 Rettungshundestaffel", "5 Dienstgruppenleitung-Erweiterung"],
	["20 Feuerwache", "10 Polizeiwache", "10 Rettungswache", "5 THW-Ortsverband", "1 Rettungshundestaffel"],
	["20 Feuerwache", "15 Polizeiwache", "10 Rettungswache", "5 THW-Ortsverband", "1 Rettungshundestaffel", "10 Dienstgruppenleitung-Erweiterung"],
	["8 Feuerwache", "3 Polizeiwache", "10 Rettungswache", "3 THW-Ortsverband", "1 Rettungshundestaffel"],
	["8 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "3 THW-Ortsverband", "1 Rettungshundestaffel", "5 Dienstgruppenleitung-Erweiterung"],
	["1 Feuerwache", "7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Rettungswache"],
	["3 Feuerwache", "1 Polizeiwache", "6 Rettungswache", "2 THW-Ortsverband", "2 Rettungshundestaffeln"],
	["3 Feuerwache", "7 Polizeiwache", "6 Rettungswache", "2 THW-Ortsverband", "2 Rettungshundestaffeln", "5 Dienstgruppenleitung-Erweiterung"],
	["30 Feuerwache", "5 Polizeiwache", "20 Rettungswache", "1 Bereitschaftspolizei", "5 THW-Ortsverband", "2 Rettungshundestaffeln"],
	["30 Feuerwache", "7 Polizeiwache", "20 Rettungswache", "1 Bereitschaftspolizei", "5 THW-Ortsverband", "2 Rettungshundestaffeln", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "1 THW-Ortsverband", "1 Rettungshundestaffel", "5 Dienstgruppenleitung-Erweiterung"],
	["16 Feuerwache", "4 Polizeiwache", "14 Rettungswache", "3 THW-Ortsverband", "1 Rettungshundestaffel"],
	["16 Feuerwache", "7 Polizeiwache", "14 Rettungswache", "3 THW-Ortsverband", "1 Rettungshundestaffel", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "2 Polizeiwache", "8 Rettungswache", "2 THW-Ortsverband", "1 Rettungshundestaffel"],
	["13 Feuerwache", "7 Polizeiwache", "8 Rettungswache", "2 THW-Ortsverband", "1 Rettungshundestaffel", "5 Dienstgruppenleitung-Erweiterung"],
	["14 Feuerwache", "5 Polizeiwache", "3 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["1 MEK-Wache"],
	["10 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Polizeiwache", "3 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["9 Feuerwache", "5 Polizeiwache", "6 Rettungswache"],
	["9 Feuerwache", "7 Polizeiwache", "6 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "3 Polizeiwache", "7 Rettungswache"],
	["10 Feuerwache", "7 Polizeiwache", "7 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["3 Feuerwache", "12 Polizeiwache", "2 Rettungswache", "1 Bereitschaftspolizei", "1 SEG-Wache"],
	["3 Feuerwache", "15 Polizeiwache", "2 Rettungswache", "1 Bereitschaftspolizei", "1 SEG-Wache", "10 Dienstgruppenleitung-Erweiterung"],
	["4 Polizeiwache", "1 MEK-Wache"],
	["5 Polizeiwache", "1 MEK-Wache"],
	["7 Polizeiwache", "1 MEK-Wache", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "2 Bereitschaftspolizei", "1 Polizeihubschrauberstation"],
	["7 Polizeiwache", "2 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Polizeiwache", "1 SEK-Wache", "2 Rettungswache"],
	["7 Polizeiwache", "1 SEK-Wache", "2 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "3 Polizeiwache", "1 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "7 Polizeiwache", "2 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "5 Dienstgruppenleitung-Erweiterung"],
	["14 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["11 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["14 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["14 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["8 Polizeiwache", "3 Rettungswache", "1 Bereitschaftspolizei"],
	["8 Polizeiwache", "3 Rettungswache", "1 Bereitschaftspolizei", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "10 Rettungswache", "1 Bereitschaftspolizei", "1 Polizeihubschrauberstation"],
	["15 Polizeiwache", "10 Rettungswache", "1 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "10 Dienstgruppenleitung-Erweiterung"],
	["22 Feuerwache", "7 Polizeiwache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["32 Feuerwache", "8 Polizeiwache", "9 Rettungswache", "3 THW-Ortsverband"],
	["32 Feuerwache", "15 Polizeiwache", "9 Rettungswache", "3 THW-Ortsverband", "10 Dienstgruppenleitung-Erweiterung"],
	["18 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["10 Polizeiwache", "10 Rettungswache", "2 Bereitschaftspolizei", "1 Diensthundestaffel"],
	["15 Polizeiwache", "10 Rettungswache", "2 Bereitschaftspolizei", "10 Dienstgruppenleitung-Erweiterung", "1 Diensthundestaffel"],
	["14 Polizeiwache", "10 Rettungswache", "5 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "1 Diensthundestaffel"],
	["15 Polizeiwache", "10 Rettungswache", "5 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "10 Dienstgruppenleitung-Erweiterung", "1 Diensthundestaffel"],
	["6 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "4 Polizeiwache", "12 Rettungswache", "4 Wasserrettung", "1 THW-Ortsverband"],
	["15 Feuerwache", "7 Polizeiwache", "12 Rettungswache", "4 Wasserrettung", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["12 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "2 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["12 Feuerwache", "7 Polizeiwache", "1 Werkfeuerwehr", "2 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["4 Feuerwache", "5 Polizeiwache", "3 Rettungswache", "1 THW-Ortsverband", "3 Dienstgruppenleitung-Erweiterung"],
	["16 Feuerwache", "4 Polizeiwache", "10 Rettungswache", "1 THW-Ortsverband"],
	["16 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["7 Polizeiwache", "1 Kriminalpolizei-Ausbau", "5 Dienstgruppenleitung-Erweiterung"],
	["3 Polizeiwache", "1 Kriminalpolizei-Ausbau", "1 Diensthundestaffel"],
	["7 Polizeiwache", "1 Kriminalpolizei-Ausbau", "5 Dienstgruppenleitung-Erweiterung", "1 Diensthundestaffel"],
	["4 Polizeiwache", "1 Polizeihubschrauberstation", "1 Kriminalpolizei-Ausbau", "1 Diensthundestaffel"],
	["7 Polizeiwache", "1 Polizeihubschrauberstation", "1 Kriminalpolizei-Ausbau", "5 Dienstgruppenleitung-Erweiterung", "1 Diensthundestaffel"],
	["10 Polizeiwache", "1 MEK-Wache", "1 Rettungswache", "1 Polizeihubschrauberstation", "2 Kriminalpolizei-Ausbau"],
	["10 Polizeiwache", "1 MEK-Wache", "1 Rettungswache", "1 Polizeihubschrauberstation", "2 Kriminalpolizei-Ausbau", "5 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["12 Feuerwache", "2 Polizeiwache", "3 Rettungswache", "1 Dienstgruppenleitung-Erweiterung"],
	["9 Feuerwache", "2 Polizeiwache", "1 Dienstgruppenleitung-Erweiterung"],
	["9 Feuerwache", "2 Polizeiwache", "1 Dienstgruppenleitung-Erweiterung"],
	["7 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["5 Feuerwache", "7 Polizeiwache", "2 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["17 Feuerwache", "7 Polizeiwache", "5 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["13 Feuerwache", "7 Polizeiwache", "2 THW-Ortsverband", "1 Fachgruppe Wasserschaden/Pumpen Erweiterung", "5 Dienstgruppenleitung-Erweiterung"],
	["25 Feuerwache", "8 Polizeiwache", "2 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "5 THW-Ortsverband", "2 Fachgruppe Wasserschaden/Pumpen Erweiterung"],
	["25 Feuerwache", "15 Polizeiwache", "2 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "5 THW-Ortsverband", "2 Fachgruppe Wasserschaden/Pumpen Erweiterung", "10 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "4 THW-Ortsverband", "2 Fachgruppe Wasserschaden/Pumpen Erweiterung"],
	["15 Feuerwache", "2 Polizeiwache", "4 THW-Ortsverband", "2 Fachgruppe Wasserschaden/Pumpen Erweiterung"],
	["15 Feuerwache", "2 Polizeiwache", "4 THW-Ortsverband", "2 Fachgruppe Wasserschaden/Pumpen Erweiterung", "1 Dienstgruppenleitung-Erweiterung"],
	["15 Feuerwache", "6 Polizeiwache", "5 Wasserrettung", "3 THW-Ortsverband", "2 Fachgruppe Wasserschaden/Pumpen Erweiterung"],
	["15 Feuerwache", "15 Polizeiwache", "5 Wasserrettung", "3 THW-Ortsverband", "2 Fachgruppe Wasserschaden/Pumpen Erweiterung", "10 Dienstgruppenleitung-Erweiterung"],
	["10 Feuerwache", "2 Polizeiwache", "10 Rettungswache"],
	["10 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["8 Feuerwache", "7 Polizeiwache", "4 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["20 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "1 THW-Ortsverband", "5 Dienstgruppenleitung-Erweiterung"],
	["30 Feuerwache", "6 Polizeiwache", "10 Rettungswache", "3 THW-Ortsverband"],
	["7 Polizeiwache", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"],
	["8 Polizeiwache", "12 Rettungswache", "3 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "2 Kriminalpolizei-Ausbau", "2 Diensthundestaffeln"],
	["8 Polizeiwache", "12 Rettungswache", "3 Bereitschaftspolizei", "1 Polizeihubschrauberstation", "2 Kriminalpolizei-Ausbau", "5 Dienstgruppenleitung-Erweiterung", "2 Diensthundestaffeln"],
	["10 Feuerwache", "4 Polizeiwache", "8 Rettungswache"],
	["7 Feuerwache", "3 Polizeiwache", "15 Rettungswache"],
	["7 Feuerwache", "5 Polizeiwache", "5 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["8 Feuerwache", "7 Polizeiwache", "3 Rettungswache", "5 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "5 Polizeiwache", "4 Rettungswache", "3 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "2 Polizeiwache", "10 Rettungswache"],
	["20 Feuerwache", "4 Polizeiwache", "18 Rettungswache", "1 THW-Ortsverband"],
	["20 Feuerwache", "4 Polizeiwache", "18 Rettungswache", "1 THW-Ortsverband", "1 Dienstgruppenleitung-Erweiterung"],
	["6 Feuerwache", "2 Polizeiwache", "1 Rettungswache", "2 Wasserrettung"],
	["11 Feuerwache", "5 Polizeiwache", "1 Bereitschaftspolizei", "1 Kriminalpolizei-Ausbau"],
	["11 Feuerwache", "7 Polizeiwache", "1 Bereitschaftspolizei", "1 Kriminalpolizei-Ausbau", "5 Dienstgruppenleitung-Erweiterung"],
	["25 Feuerwache", "2 Polizeiwache", "10 Rettungswache", "1 Polizeihubschrauberstation"],
	["25 Feuerwache", "7 Polizeiwache", "10 Rettungswache", "1 Polizeihubschrauberstation", "5 Dienstgruppenleitung-Erweiterung"]
]